language: ja-JP

reviews:
  auto_review:
    enabled: true
    drafts: true
  profile: chill
  high_level_summary: true
  poem: false  # 必要なければfalse
  review_status: true

path_filters:
  - "!*.lock"
  - "!*.log"
  - "!*.md"
  - "!package-lock.json"
  - "!pnpm-lock.yaml"
  - "!yarn.lock"
  - "!.next/**"
  - "!node_modules/**"
  - "!public/**"
  - "!.env*"

path_instructions:
  - path: "**/*.ts"
    instructions: "TypeScriptのベストプラクティスに従ってレビューしてください。型安全性を重視してください。"
  - path: "**/*.tsx"
    instructions: "Reactのベストプラクティスに従ってレビューしてください。パフォーマンスとアクセシビリティを重視してください。"
  - path: "**/*.sql"
    instructions: "SQLのセキュリティとパフォーマンスを重視してレビューしてください。"

chat:
  enabled: true